import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_project2/models/restaurants_model.dart';

import 'cart_model.dart';

/*class OrderModel {
  String? id;
  String? img;
  String? item;
  String? itemName;
  String? itemPrice;
  int? quantity;
  String? restaurantId;
  List<CartModel>? orderItems;

  OrderModel({
    required this.id,
    this.img,
    this.item,
    required this.itemName,
    required this.itemPrice,
    this.quantity,
    this.restaurantId,
    this.orderItems,
  });

  OrderModel.fromJson(Map<String, dynamic> json)
      : id = json['id'] as String,
        img = json['img'] as String,
        item = json['item'] as String,
        itemName = json['name'] as String,
        itemPrice = json['itemPrice'] as String,
        quantity = json['quantity'] as int,
        restaurantId = json['restaurantId'] as String,
        orderItems = (json['orderItems'] as List)
            .map((dynamic e) => CartModel.fromJson(e as Map<String, dynamic>))
            .toList();

  OrderModel.fromSnapshot(DocumentSnapshot<Map<String, dynamic>> json)
      : id = json.id,
        img = json['img'],
        item = json['item'],
        itemName = json['itemName'],
        itemPrice = json['itemPrice'],
        quantity = json['quantity'],
        restaurantId = json['restaurantId'],
        orderItems = [];
}*/

class Autogenerated {
  String? id;
  List<OrderItems>? orderItems;

  Autogenerated({this.id, this.orderItems});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    if (json['orderItems'] != null) {
      orderItems = <OrderItems>[];
      json['orderItems'].forEach((v) {
        orderItems!.add(new OrderItems.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    if (this.orderItems != null) {
      data['orderItems'] = this.orderItems!.map((v) => v.toJson()).toList();
    }
    return data;
  }

  Autogenerated.fromSnapshot(DocumentSnapshot<Map<String, dynamic>> json)
      : id = json.id,
        orderItems = [];
}

class OrderItems {
  String? id;
  String? img;
  String? item;
  String? itemName;
  String? itemPrice;
  int? quantity;
  String? restaurantId;

  OrderItems(
      {this.id,
        this.img,
        this.item,
        this.itemName,
        this.itemPrice,
        this.quantity,
        this.restaurantId});

  OrderItems.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    img = json['img'];
    item = json['item'];
    itemName = json['itemName'];
    itemPrice = json['itemPrice'];
    quantity = json['quantity'];
    restaurantId = json['restaurantId'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['img'] = this.img;
    data['item'] = this.item;
    data['itemName'] = this.itemName;
    data['itemPrice'] = this.itemPrice;
    data['quantity'] = this.quantity;
    data['restaurantId'] = this.restaurantId;
    return data;
  }

  OrderItems.fromSnapshot(DocumentSnapshot<Map<String, dynamic>> json)
      : id = json.id,
        img = json['img'],
        item = json['item'],
        itemName = json['itemName'],
        itemPrice = json['itemPrice'],
        quantity = json['quantity'],
        restaurantId = json['restaurantId'];
}
